# Generated by Django 3.1.7 on 2021-08-20 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Marka')),
                ('model', models.CharField(max_length=50, verbose_name='Model')),
                ('city', models.CharField(choices=[('Baki', 'Bakı'), ('Gəncə', 'Gəncə'), ('Naxçıvan', 'Naxçıvan'), ('Xankəndi', 'Xankəndi'), ('Lənkəran', 'Lənkəran'), ('Mingəçevir', 'Mingəçevir'), ('Naftalan', 'Naftalan'), ('Sumqayıt', 'Sumqayıt'), ('Şəki', 'Şəki'), ('Şirvan', 'Şirvan'), ('Yevlax', 'Yevlax'), ('Abşeron', 'Abşeron'), ('Ağcabədi', 'Ağcabədi'), ('Ağdam', 'Ağdam'), ('Ağdaş', 'Ağdaş'), ('Ağstafa', 'Ağstafa'), ('Ağsu', 'Ağsu'), ('Astara', 'Astara'), ('Babək', 'Babək'), ('Beyləqan', 'Beyləqan'), ('Bərdə', 'Bərdə'), ('Biləsuvar', 'Biləsuvar'), ('Cəbrayıl', 'Cəbrayıl'), ('Cəlilabad', 'Cəlilabad'), ('Culfa', 'Culfa'), ('Daşkəsən', 'Daşkəsən'), ('Füzuli', 'Füzuli'), ('Gədəbəy', 'Gədəbəy'), ('Goranboy', 'Goranboy'), ('Göyçay', 'Göyçay'), ('Göygöl', 'Göygöl'), ('Hacıqabul', 'Hacıqabul'), ('Xaçmaz', 'Xaçmaz'), ('Xızı', 'Xızı'), ('Xocalı', 'Xocalı'), ('Xocavənd', 'Xocavənd'), ('İmişli', 'İmişli'), ('Kəlbəcər', 'Kəlbəcər'), ('Kürdəmir', 'Kürdəmir'), ('Qax', 'Qax'), ('Qazax', 'Qazax'), ('Qəbələ', 'Qəbələ')], max_length=50, verbose_name='Şəhər')),
                ('engine', models.CharField(max_length=50, verbose_name='Mühərrik')),
                ('body_type', models.CharField(choices=[('Avtobus', 'Avtobus'), ('Buldozer', 'Buldozer'), ('İcma Maşını', 'İcma Maşını'), ('Skuter', 'Skuter'), ('ATV', 'ATV'), ('Qar avtomobili', 'Qar avtomobili'), ('SUV', 'SUV'), ('Ekskavator', 'Ekskavator'), ('Yük kranı', 'Yük kranı'), ('Yükləyici', 'Yükləyici'), ('Tikinti və yol', 'Tikinti və yol'), ('Kənd təsərrüfatı', 'Kənd təsərrüfatı'), ('Yarı qoşqu traktoru', 'Yarı qoşqu traktoru'), ('Yük maşını', 'Yük maşını'), ('Yüngül kommersiya', 'Yüngül kommersiya'), ('Qoşqu və yarı qoşqu', 'Qoşqu və yarı qoşqu'), ('Furqon', 'Furqon'), ('Hetçbek', 'Hetçbek'), ('Liftbek', 'Liftbek'), ('Kabriolet', 'Kabriolet'), ('Karvan', 'Karvan'), ('Kupe', 'Kupe'), ('Kvadrosikl', 'Kvadrosikl'), ('Mikroavtobus', 'Mikroavtobus'), ('Minivan', 'Minivan'), ('Motosiklet', 'Motosiklet'), ('Offroader / SUV', 'Offroader / SUV'), ('Pikap', 'Pikap'), ('Qolfkar', 'Qolfkar'), ('Rodster', 'Rodster'), ('Sedan', 'Sedan'), ('Universal', 'Universal'), ('Van', 'Van'), ('Yük maşını', 'Yük maşını')], max_length=50, verbose_name='Ban Növü')),
                ('transmission', models.CharField(choices=[('Mexaniki', 'Mexaniki'), ('Avtomat', 'Avtomat'), ('Robotlaşdırılmış', 'Robotlaşdırılmış'), ('Variator', 'Variator')], max_length=50, verbose_name='Sürətlər qutusu')),
                ('milage', models.PositiveIntegerField(default='0', verbose_name='Yürüş, km')),
                ('color', models.CharField(choices=[('Qara', 'Qara'), ('Yaş Asfalt', 'Yaş Asfalt'), ('Boz', 'Boz'), ('Gümüşü', 'Gümüşü'), ('Ağ', 'Ağ'), ('Bej', 'Bej'), ('Tünd qırmızı', 'Tünd qırmızı'), ('Qırmızı', 'Qırmızı'), ('Çəhrayı', 'Çəhrayı'), ('Narıncı', 'Narıncı'), ('Qızılı', 'Qızılı'), ('Sarı', 'Sarı'), ('Yaşıl', 'Yaşıl'), ('Mavi', 'Mavi'), ('Göy', 'Göy'), ('Bənövşəyi', 'Bənövşəyi'), ('Qəhvəyi', 'Qəhvəyi')], max_length=50, verbose_name='Rəngi')),
                ('fueltype', models.CharField(choices=[('Benzin', 'Benzin'), ('Dizel', 'Dizel'), ('Qaz', 'Qaz'), ('Elektro', 'Elektro'), ('Hibrid', 'Hibrid')], max_length=50, verbose_name='Yanacaq növü')),
                ('year', models.CharField(choices=[('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021')], max_length=50, verbose_name='Buraxılış ili')),
                ('power', models.PositiveIntegerField(default='0', verbose_name='Mühərrikin gücü, a.g.')),
                ('price', models.PositiveIntegerField(default='500', verbose_name='Qiyməti')),
                ('currencie', models.CharField(choices=[('Azn ₼', 'Azn ₼'), ('Euro €', 'Euro €'), ('USD $', 'USD $')], max_length=10, verbose_name='Məzənnə')),
                ('credit', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Kreditdədir', 'Kreditdədir'), ('Barter mümkündür', 'Barter mümkündür')], default='', max_length=28, verbose_name='')),
                ('info', models.TextField(blank=True, default='', max_length=400, verbose_name='Əlavə Məlumat')),
                ('supply', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Yüngül lehimli disklər', 'Yüngül lehimli disklər'), ('Mərkəzi qapanma', 'Mərkəzi qapanma'), ('Dəri salon', 'Dəri salon'), ('Oturacaqların ventilyasiyası', 'Oturacaqların ventilyasiyas'), ('ABS', 'ABS'), ('Park radarı', 'Park radarı'), ('Ksenon lampalar', 'Ksenon lampalar'), ('Lyuk', 'Lyuk'), ('Arxa görüntü kamerası', 'Arxa görüntü kamerası'), ('Yağış sensoru', 'Yağış sensoru'), ('Oturacaqların isidilməsi', 'Oturacaqların isidilməsi'), ('Yan pərdələr', 'Yan pərdələr')], default='', max_length=189, verbose_name='Təchizat')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Əlavə olunma tarixi')),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('compare', models.ManyToManyField(blank=True, related_name='compare', to=settings.AUTH_USER_MODEL)),
                ('favourite', models.ManyToManyField(blank=True, related_name='favourite', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='car.car')),
            ],
        ),
    ]
