# Generated by Django 3.1.7 on 2021-09-16 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_car_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='phonenumber',
        ),
    ]
