# Generated by Django 3.1.7 on 2021-08-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpareParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(choices=[('Təkərlər və disklər', 'Təkərlər və disklər'), ('Yağlar və avtomobil kimyəvi maddələr', 'Yağlar və avtomobil kimyəvi maddələr'), ('Akkumlyatorlar', 'Akkumlyatorlar'), ('Bədən hissələri', 'Bədən hissələri'), ('Elektrik və işıq', 'Elektrik və işıq'), ('Mühərrik və alovlanma sistemi', 'Mühərrik və alovlanma sistemi'), ('Aksesuarlar', 'Aksesuarlar'), ('Alətlər', 'Alətlər')], max_length=120, verbose_name='Növü')),
                ('marka', models.CharField(max_length=50, verbose_name='Markası')),
                ('qiymet', models.PositiveIntegerField(default='0', verbose_name='Qiyməti')),
                ('sheher', models.CharField(max_length=50, verbose_name='Şəhər')),
                ('mezenne', models.CharField(choices=[('Azn ₼', 'Azn ₼'), ('Euro €', 'Euro €'), ('USD $', 'USD $')], default='', max_length=10, verbose_name='Məzənnə')),
                ('shekil', models.FileField(null=True, upload_to='', verbose_name='Shekil elave et:')),
                ('info', models.TextField(blank=True, default='', max_length=400, verbose_name='Əlavə Məlumat')),
            ],
        ),
    ]
